name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build Stage
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
    
    - name: Build with Maven
      run: mvn clean package
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: target/*.jar

  # Test Stage
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
    
    - name: Run tests
      run: mvn test
    
    - name: Run code quality checks
      run: mvn checkstyle:check

  # Deploy Stage
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Deploy to staging environment
      run: echo "Deploying application to staging environment..."
      # Replace this with actual deployment commands, such as SCP or SSH
      # Example: scp target/*.jar user@server:/path/to/staging/
